ProjetConsommant/Controllers/ProduitXrayController.cs
using ProjetConsommant.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace ProjetConsommant.Controllers
{
    public class ProduitXrayController : Controller
    {
        // GET: ProduitXray
        public ActionResult Index()
        {
            IEnumerable<mvcProduitModel> x;
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833/");//////////////////
            client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //4.getasync ;recuperer les resultats :
            HttpResponseMessage response = client.GetAsync("api/Produits").Result;
            x = response.Content.ReadAsAsync<IEnumerable<mvcProduitModel>>().Result;
            return View(x);
        }

        public ActionResult Create()
        {
            IEnumerable<Categorie> x;
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833/");//////////////////
            client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //4.getasync ;recuperer les resultats :
            HttpResponseMessage response = client.GetAsync("api/Categories").Result;
            x = response.Content.ReadAsAsync<IEnumerable<Categorie>>().Result;
            ViewBag.idCategorie = new SelectList(x, "idCategorie", "nomCategorie");
            return View();
        }
        [HttpPost]
        public ActionResult Create(mvcProduitModel produit, HttpPostedFileBase ImageFile)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833/");//////////////////
            client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            //4.getasync ;recuperer les resultats :
            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string extension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            produit.nomPhoto = "~/Image/" + fileName;
            string path = Path.Combine(Server.MapPath("~/Image/"), fileName);
            ImageFile.SaveAs(path);

            HttpResponseMessage response = client.PostAsJsonAsync("api/Produits", produit).Result;
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            mvcProduitModel x;
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833");
            client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("Application/json"));

                HttpResponseMessage response = client.GetAsync("api/Produits/" + id.ToString()).Result;
                x = response.Content.ReadAsAsync<mvcProduitModel>().Result;
                return View(x);
        }

        [HttpPost]
        public ActionResult Edit(mvcProduitModel produit, HttpPostedFileBase ImageFile)
        {

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833");
            client.DefaultRequestHeaders.Accept.
                Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("Application/json"));

            string fileName = Path.GetFileNameWithoutExtension(ImageFile.FileName);
            string extension = Path.GetExtension(ImageFile.FileName);
            fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
            produit.nomPhoto = "~/Image/" + fileName;
            string path = Path.Combine(Server.MapPath("~/Image/"), fileName);
            ImageFile.SaveAs(path);
                HttpResponseMessage response = client.PutAsJsonAsync("api/Produits/" + produit.idProduit, produit).Result;
                TempData["SuccessMessage"] = "Update Succefully";

            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {

            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:1833");
            client.DefaultRequestHeaders.Accept.
            Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("Application/json"));
            HttpResponseMessage response = client.DeleteAsync("api/Produits/" + id.ToString()).Result;
            TempData["SuccessMessage"] = "Delete Succefully";
            return RedirectToAction("Index");
        }














    }
}

ProjetConsommant/Views/ProduitXray/Create.cshtml
@model ProjetConsommant.Models.mvcProduitModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2> Add New Products : </h2>

@using (Html.BeginForm("Create", "ProduitXray", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>mvcProduitModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bestProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.bestProduct)
                    @Html.ValidationMessageFor(model => model.bestProduct, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" required class="control-label col-md-2" />
                @Html.ValidationMessageFor(model => model.nomPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.idCategorie, "Categorie", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idCategorie", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idCategorie, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetConsommant/Views/ProduitXray/Edit.cshtml
@model ProjetConsommant.Models.mvcProduitModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Edit</h2>

@using (Html.BeginForm("Create", "ProduitXray", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>mvcProduitModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idProduit)

        <div class="form-group">
            @Html.LabelFor(model => model.designation, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.designation, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.designation, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bestProduct, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.bestProduct)
                    @Html.ValidationMessageFor(model => model.bestProduct, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nomPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="ImageFile" id="ImageFile" required class="control-label col-md-2" />
                @Html.ValidationMessageFor(model => model.nomPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.quantite, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.quantite, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.quantite, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.prix, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idCategorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.idCategorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.idCategorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ProjetConsommant/Views/ProduitXray/Index.cshtml
@model IEnumerable<ProjetConsommant.Models.mvcProduitModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.designation)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.bestProduct)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.nomPhoto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.quantite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.prix)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idCategorie)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.designation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bestProduct)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.color)
            </td>
            <td>
                <img src="@Url.Content(item.nomPhoto)" width="90" height="80" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.prix)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categorie.nomCategorie)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.idProduit }) |

                @Html.ActionLink("Delete", "Delete", new { id = item.idProduit })
            </td>
        </tr>
    }

</table>